services:
  app-backend-dev:
    ports:
      - "8000:8000"
    image: "alejovicu/app-backend:1.0.3"
  app-frontend:
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    deploy:
      resources:
        limits:
          memory: 4G
    image: "app-frontend"